// import type { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'

// import { groq } from 'next-sanity'
// import { getClient, usePreviewSubscription } from '@lib/sanity'
// import { useRouter } from 'next/router'
import Header from '@components/Header'
import Footer from '@components/Footer'
import Frontpage from '@components/Frontpage'
// function Home ({ postdata, preview }: InferGetStaticPropsType<typeof getStaticProps>)
function Home () {
  // const router = useRouter()

  // const { data: posts } = usePreviewSubscription<any>(query, {
  //   initialData: postdata,
  //   enabled: preview || router.query.preview !== undefined
  // })

  return (
    <div className='m-0 p-0'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Header/>

      <Frontpage/>
      <div className='py-10'></div>
      {/* {posts &&
        posts.map((post: any, idx:any) => (
          <article key={idx}>
            <h3 className="text-lg"> {post.title} </h3>
            <p className="mt-3">{post.excerpt}</p>
          </article>
        ))} */}
      </main>

      <Footer/>
    </div>
  )
}

// const query = groq`
//   *[_type == "post"] | order(_createdAt desc) {
//     ...,
//     author->,
//     categories[]->
//   }
// `

// export const getStaticProps: GetStaticProps = async ({ params, preview = false }) => {
//   const post = await getClient(preview).fetch(query)

//   return {
//     props: {
//       postdata: post,
//       preview
//     },
//     revalidate: 10
//   }
// }

export default Home
