import type { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { groq } from 'next-sanity'
import { getClient, usePreviewSubscription } from '@lib/sanity'
import { useRouter } from 'next/router'

function Home ({ postdata, preview }: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(postdata)

  const router = useRouter()

  const { data: posts } = usePreviewSubscription<any>(query, {
    initialData: postdata,
    enabled: preview || router.query.preview !== undefined
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

      {posts &&
        posts.map((post: any, idx:any) => (
          <article key={idx}>
            <h3 className="text-lg"> {post.title} </h3>
            <p className="mt-3">{post.excerpt}</p>
          </article>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const query = groq`
  *[_type == "post"] | order(_createdAt desc) {
    ...,
    author->,
    categories[]->
  }
`

export const getStaticProps: GetStaticProps = async ({ params, preview = false }) => {
  const post = await getClient(preview).fetch(query)

  return {
    props: {
      postdata: post,
      preview
    },
    revalidate: 10
  }
}

export default Home
